cd /usr/src/hw3-cse506g/hw3
make clean
make
sh install_modules.sh
echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis diam eget nisi hendrerit finibus. Donec semper risus eu egestas efficitur. Vestibulum lorem nisi, venenatis ut lobortis ac, ornare quis urna. Proin volutpat ligula et egestas maximus. Ut volutpat tristique libero a iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut a hendrerit leo. Vivamus rutrum mauris vitae sem pulvinar, sit amet egestas ipsum molestie. Donec varius est eget libero imperdiet ultrices. Ut at lacinia mauris, nec molestie erat. Cras pretium auctor elit sed varius. Curabitur eu aliquet velit. Proin eget magna sit amet sapien fermentum fringilla eget nec odio.

Sed gravida dapibus nunc, vitae euismod augue finibus at. Aliquam congue ultrices orci, quis vehicula risus gravida ut. Nulla sed tellus diam. Sed orci massa, dictum at blandit sed, gravida dignissim mauris. Ut quis ipsum et nibh scelerisque tincidunt. Pellentesque vitae ultrices diam. Nulla facilisi. Aliquam erat volutpat. Praesent dui turpis, fermentum sed dui eget, venenatis faucibus lacus. Nulla bibendum vehicula tortor eget placerat. Ut consequat dolor magna, non consequat lorem aliquet non. Praesent placerat placerat consequat. Mauris fringilla pulvinar nunc, at eleifend orci cursus sit amet.

Praesent sed ornare diam. In pretium vehicula urna, vitae cursus felis auctor rhoncus. Ut vitae neque tristique, laoreet diam accumsan, dapibus nisi. Morbi molestie pretium ante sed malesuada. Mauris interdum non massa at sagittis. Donec sed neque sodales, imperdiet arcu eget, pretium ex. Aliquam erat volutpat. Vestibulum sollicitudin eros id mi ultricies, ut volutpat ex dapibus. Integer placerat pellentesque odio, ac sollicitudin velit lobortis non. Praesent semper mollis lorem. Nunc id pretium nisi. In sollicitudin pellentesque sapien vitae volutpat. Duis vel tellus leo. Nulla vel orci mollis, eleifend risus ut, ultricies est. Mauris congue suscipit diam vel luctus. Donec in arcu metus.

Praesent venenatis finibus dolor ac vestibulum. In sagittis orci vitae nibh consectetur vestibulum. Ut porta, libero et mollis hendrerit, arcu magna luctus diam, in blandit tortor ipsum id turpis. Donec ut cursus turpis. Duis aliquam, mauris vitae gravida posuere, quam tellus suscipit metus, sit amet fermentum metus libero vel sapien. Suspendisse rhoncus dictum nunc ac aliquet. Aenean et risus lacinia, malesuada nisl sed, mollis orci.

Fusce sed placerat felis. Ut elementum nibh vestibulum sollicitudin fermentum. Suspendisse lacus nisi, iaculis sit amet neque eu, pharetra semper nunc. Integer vitae magna ac enim sollicitudin suscipit mattis eu justo. Vestibulum et sagittis purus. Donec sed urna et nisi iaculis ultricies nec viverra nisi. Nunc eu scelerisque magna. Morbi bibendum luctus magna, non feugiat diam ornare suscipit. Nam cursus est nec dignissim porttitor. Mauris iaculis magna velit, ut suscipit nisl porta at. Praesent urna metus, luctus sed nibh id, euismod sagittis mauris. Maecenas ac est in sapien scelerisque pretium quis et nulla. Sed eget convallis dui. Praesent sit amet ultricies risus, vel ultrices lorem. Suspendisse potenti. Phasellus sollicitudin malesuada odio, vel molestie nisl iaculis ut.

Vivamus semper eleifend lacus, id dignissim lacus porttitor ut. Pellentesque blandit orci id quam ultricies ultrices. Sed facilisis pharetra ipsum non pulvinar. Quisque in fermentum nulla, nec consectetur purus. Donec eget sem faucibus, imperdiet lorem vitae, bibendum dolor. Aliquam elementum tortor eget tortor congue, viverra dictum diam aliquam. Curabitur scelerisque orci tincidunt nisl consequat posuere. Donec ante sapien, lacinia vel convallis at, venenatis vel nunc. Integer at neque fringilla, cursus purus ut, malesuada dolor. Curabitur id dapibus magna, non varius magna. Nullam sit amet orci fermentum, pharetra magna nec, iaculis purus. Phasellus urna odio, placerat sed imperdiet id, tempor ac nisi. Donec tincidunt tempor consectetur. Sed consequat ante et est ultrices, vitae ultricies odio placerat. Cras lacinia eleifend velit, ut pellentesque lacus iaculis eget. Nullam ullamcorper diam turpis, sed eleifend nisi convallis quis.

Maecenas iaculis nec sem ut molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque vehicula finibus sapien, sit amet interdum mi varius et. Cras sollicitudin leo ac elit malesuada dapibus. Duis iaculis efficitur dictum. Pellentesque habitant morbi tristique posuere." >temp1.txt
./xclone22 -m temp1.txt

echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis diam eget nisi hendrerit finibus. Donec semper risus eu egestas efficitur. Vestibulum lorem nisi, venenatis ut lobortis ac, ornare quis urna. Proin volutpat ligula et egestas maximus. Ut volutpat tristique libero a iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut a hendrerit leo. Vivamus rutrum mauris vitae sem pulvinar, sit amet egestas ipsum molestie. Donec varius est eget libero imperdiet ultrices. Ut at lacinia mauris, nec molestie erat. Cras pretium auctor elit sed varius. Curabitur eu aliquet velit. Proin eget magna sit amet sapien fermentum fringilla eget nec odio.

Sed gravida dapibus nunc, vitae euismod augue finibus at. Aliquam congue ultrices orci, quis vehicula risus gravida ut. Nulla sed tellus diam. Sed orci massa, dictum at blandit sed, gravida dignissim mauris. Ut quis ipsum et nibh scelerisque tincidunt. Pellentesque vitae ultrices diam. Nulla facilisi. Aliquam erat volutpat. Praesent dui turpis, fermentum sed dui eget, venenatis faucibus lacus. Nulla bibendum vehicula tortor eget placerat. Ut consequat dolor magna, non consequat lorem aliquet non. Praesent placerat placerat consequat. Mauris fringilla pulvinar nunc, at eleifend orci cursus sit amet.

Praesent sed ornare diam. In pretium vehicula urna, vitae cursus felis auctor rhoncus. Ut vitae neque tristique, laoreet diam accumsan, dapibus nisi. Morbi molestie pretium ante sed malesuada. Mauris interdum non massa at sagittis. Donec sed neque sodales, imperdiet arcu eget, pretium ex. Aliquam erat volutpat. Vestibulum sollicitudin eros id mi ultricies, ut volutpat ex dapibus. Integer placerat pellentesque odio, ac sollicitudin velit lobortis non. Praesent semper mollis lorem. Nunc id pretium nisi. In sollicitudin pellentesque sapien vitae volutpat. Duis vel tellus leo. Nulla vel orci mollis, eleifend risus ut, ultricies est. Mauris congue suscipit diam vel luctus. Donec in arcu metus.

Praesent venenatis finibus dolor ac vestibulum. In sagittis orci vitae nibh consectetur vestibulum. Ut porta, libero et mollis hendrerit, arcu magna luctus diam, in blandit tortor ipsum id turpis. Donec ut cursus turpis. Duis aliquam, mauris vitae gravida posuere, quam tellus suscipit metus, sit amet fermentum metus libero vel sapien. Suspendisse rhoncus dictum nunc ac aliquet. Aenean et risus lacinia, malesuada nisl sed, mollis orci.

Fusce sed placerat felis. Ut elementum nibh vestibulum sollicitudin fermentum. Suspendisse lacus nisi, iaculis sit amet neque eu, pharetra semper nunc. Integer vitae magna ac enim sollicitudin suscipit mattis eu justo. Vestibulum et sagittis purus. Donec sed urna et nisi iaculis ultricies nec viverra nisi. Nunc eu scelerisque magna. Morbi bibendum luctus magna, non feugiat diam ornare suscipit. Nam cursus est nec dignissim porttitor. Mauris iaculis magna velit, ut suscipit nisl porta at. Praesent urna metus, luctus sed nibh id, euismod sagittis mauris. Maecenas ac est in sapien scelerisque pretium quis et nulla. Sed eget convallis dui. Praesent sit amet ultricies risus, vel ultrices lorem. Suspendisse potenti. Phasellus sollicitudin malesuada odio, vel molestie nisl iaculis ut.

Vivamus semper eleifend lacus, id dignissim lacus porttitor ut. Pellentesque blandit orci id quam ultricies ultrices. Sed facilisis pharetra ipsum non pulvinar. Quisque in fermentum nulla, nec consectetur purus. Donec eget sem faucibus, imperdiet lorem vitae, bibendum dolor. Aliquam elementum tortor eget tortor congue, viverra dictum diam aliquam. Curabitur scelerisque orci tincidunt nisl consequat posuere. Donec ante sapien, lacinia vel convallis at, venenatis vel nunc. Integer at neque fringilla, cursus purus ut, malesuada dolor. Curabitur id dapibus magna, non varius magna. Nullam sit amet orci fermentum, pharetra magna nec, iaculis purus. Phasellus urna odio, placerat sed imperdiet id, tempor ac nisi. Donec tincidunt tempor consectetur. Sed consequat ante et est ultrices, vitae ultricies odio placerat. Cras lacinia eleifend velit, ut pellentesque lacus iaculis eget. Nullam ullamcorper diam turpis, sed eleifend nisi convallis quis.

Maecenas iaculis nec sem ut molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque vehicula finibus sapien, sit amet interdum mi varius et. Cras sollicitudin leo ac elit malesuada dapibus. Duis iaculis efficitur dictum. Pellentesque habitant morbi tristique posuere." >temp1.txt
echo "abcdefghij" >/proc/enc_key_file
./xclone2 -me temp1.txt

echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce facilisis diam eget nisi hendrerit finibus. Donec semper risus eu egestas efficitur. Vestibulum lorem nisi, venenatis ut lobortis ac, ornare quis urna. Proin volutpat ligula et egestas maximus. Ut volutpat tristique libero a iaculis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut a hendrerit leo. Vivamus rutrum mauris vitae sem pulvinar, sit amet egestas ipsum molestie. Donec varius est eget libero imperdiet ultrices. Ut at lacinia mauris, nec molestie erat. Cras pretium auctor elit sed varius. Curabitur eu aliquet velit. Proin eget magna sit amet sapien fermentum fringilla eget nec odio.

Sed gravida dapibus nunc, vitae euismod augue finibus at. Aliquam congue ultrices orci, quis vehicula risus gravida ut. Nulla sed tellus diam. Sed orci massa, dictum at blandit sed, gravida dignissim mauris. Ut quis ipsum et nibh scelerisque tincidunt. Pellentesque vitae ultrices diam. Nulla facilisi. Aliquam erat volutpat. Praesent dui turpis, fermentum sed dui eget, venenatis faucibus lacus. Nulla bibendum vehicula tortor eget placerat. Ut consequat dolor magna, non consequat lorem aliquet non. Praesent placerat placerat consequat. Mauris fringilla pulvinar nunc, at eleifend orci cursus sit amet.

Praesent sed ornare diam. In pretium vehicula urna, vitae cursus felis auctor rhoncus. Ut vitae neque tristique, laoreet diam accumsan, dapibus nisi. Morbi molestie pretium ante sed malesuada. Mauris interdum non massa at sagittis. Donec sed neque sodales, imperdiet arcu eget, pretium ex. Aliquam erat volutpat. Vestibulum sollicitudin eros id mi ultricies, ut volutpat ex dapibus. Integer placerat pellentesque odio, ac sollicitudin velit lobortis non. Praesent semper mollis lorem. Nunc id pretium nisi. In sollicitudin pellentesque sapien vitae volutpat. Duis vel tellus leo. Nulla vel orci mollis, eleifend risus ut, ultricies est. Mauris congue suscipit diam vel luctus. Donec in arcu metus.

Praesent venenatis finibus dolor ac vestibulum. In sagittis orci vitae nibh consectetur vestibulum. Ut porta, libero et mollis hendrerit, arcu magna luctus diam, in blandit tortor ipsum id turpis. Donec ut cursus turpis. Duis aliquam, mauris vitae gravida posuere, quam tellus suscipit metus, sit amet fermentum metus libero vel sapien. Suspendisse rhoncus dictum nunc ac aliquet. Aenean et risus lacinia, malesuada nisl sed, mollis orci.

Fusce sed placerat felis. Ut elementum nibh vestibulum sollicitudin fermentum. Suspendisse lacus nisi, iaculis sit amet neque eu, pharetra semper nunc. Integer vitae magna ac enim sollicitudin suscipit mattis eu justo. Vestibulum et sagittis purus. Donec sed urna et nisi iaculis ultricies nec viverra nisi. Nunc eu scelerisque magna. Morbi bibendum luctus magna, non feugiat diam ornare suscipit. Nam cursus est nec dignissim porttitor. Mauris iaculis magna velit, ut suscipit nisl porta at. Praesent urna metus, luctus sed nibh id, euismod sagittis mauris. Maecenas ac est in sapien scelerisque pretium quis et nulla. Sed eget convallis dui. Praesent sit amet ultricies risus, vel ultrices lorem. Suspendisse potenti. Phasellus sollicitudin malesuada odio, vel molestie nisl iaculis ut.

Vivamus semper eleifend lacus, id dignissim lacus porttitor ut. Pellentesque blandit orci id quam ultricies ultrices. Sed facilisis pharetra ipsum non pulvinar. Quisque in fermentum nulla, nec consectetur purus. Donec eget sem faucibus, imperdiet lorem vitae, bibendum dolor. Aliquam elementum tortor eget tortor congue, viverra dictum diam aliquam. Curabitur scelerisque orci tincidunt nisl consequat posuere. Donec ante sapien, lacinia vel convallis at, venenatis vel nunc. Integer at neque fringilla, cursus purus ut, malesuada dolor. Curabitur id dapibus magna, non varius magna. Nullam sit amet orci fermentum, pharetra magna nec, iaculis purus. Phasellus urna odio, placerat sed imperdiet id, tempor ac nisi. Donec tincidunt tempor consectetur. Sed consequat ante et est ultrices, vitae ultricies odio placerat. Cras lacinia eleifend velit, ut pellentesque lacus iaculis eget. Nullam ullamcorper diam turpis, sed eleifend nisi convallis quis.

Maecenas iaculis nec sem ut molestie. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque vehicula finibus sapien, sit amet interdum mi varius et. Cras sollicitudin leo ac elit malesuada dapibus. Duis iaculis efficitur dictum. Pellentesque habitant morbi tristique posuere." >temp1.txt
./xclone2 -mc temp1.txt

echo "jihgfedcba" >/proc/enc_key_file
./xclone2 -mce temp1.txt


./xclone2 -p /usr/trashbin


