cd /usr/src/hw3-cse506g/hw3
make clean
make
sh install_modules.sh
echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dignissim quis enim vel bibendum. Aliquam dui mi, rutrum a nisl ac, tincidunt lacinia ipsum. Nulla est libero, fermentum mollis egestas vel, eleifend sed velit. Etiam gravida pretium sagittis. Donec elit velit, sollicitudin et justo vitae, finibus elementum leo. Quisque facilisis ut urna et molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur purus id leo hendrerit faucibus. Sed ullamcorper, neque tincidunt hendrerit suscipit, magna arcu bibendum elit, at lacinia risus velit facilisis erat. Suspendisse eu lorem eu leo interdum dignissim vel sit amet orci. Mauris dictum posuere urna, in interdum elit. Sed sed aliquam orci, et volutpat ligula. Vivamus ex neque, tristique quis luctus ornare, dictum ac purus.

Cras in lacus velit. Ut lobortis facilisis velit vitae tempus. Aenean laoreet aliquam luctus. In vulputate laoreet metus vitae iaculis. Nunc eget dolor molestie, ultrices turpis eget, lacinia nibh. Phasellus ornare, elit vestibulum ullamcorper auctor, est magna porttitor felis, faucibus dignissim lacus lectus id lorem. Duis dignissim lacus quis metus ultrices viverra in in magna. Nullam maximus convallis enim sit amet consequat. Vivamus ut lectus est. Ut a leo a augue faucibus imperdiet. Vestibulum in ligula at massa ultrices porta in eu mi. Morbi tincidunt varius sapien, quis faucibus dolor venenatis et. Nullam aliquam consectetur nulla.

Suspendisse enim est, aliquam eu eros ut, lacinia vulputate nisi. Quisque vel convallis risus. Phasellus vitae diam congue magna tincidunt hendrerit. Nam eget sem turpis. Nam tellus metus, pulvinar ut commodo a, viverra id dui. Morbi posuere odio erat, mollis pharetra nulla dictum non. Nullam dignissim auctor diam, id aliquam massa volutpat in. Pellentesque efficitur urna ut nulla consectetur pellentesque quis ac sapien. Sed sed ex dolor. Quisque quis velit nec quam euismod vehicula. Mauris semper tincidunt sodales. Vivamus sodales lacus vel urna vestibulum, vitae iaculis enim facilisis. Nulla ut magna vitae arcu pulvinar tristique id eu nibh. Suspendisse sed rutrum dolor. Aliquam lectus erat, viverra at lacus eu, luctus egestas ipsum. Morbi elementum mauris ac lorem sagittis laoreet.

Aliquam faucibus, lacus vitae vulputate venenatis, est eros gravida dui, at maximus urna libero ac sapien. Sed tempus nibh euismod, consectetur tellus in, cursus mauris. Donec velit tortor, volutpat vel enim eget, tempus efficitur ligula. Nulla elit libero, mollis a erat vitae, tempus posuere tortor. Morbi blandit odio massa, ut hendrerit est suscipit pellentesque. Nam ex lacus, cursus a lacus eu, efficitur ultrices ligula. Quisque egestas, ipsum vitae ornare semper, sem elit scelerisque mauris, a dictum ante neque sit amet felis. Cras nec sapien viverra mauris maximus varius. Morbi mi nisl, maximus tincidunt risus in, luctus lobortis tellus.

Proin eu ex arcu. Pellentesque posuere, magna vitae tempor varius, leo ligula viverra risus, sed tempor enim lacus in justo. Duis gravida ullamcorper bibendum. Integer facilisis nisi mollis enim tempus, sit amet tincidunt quam convallis. Donec hendrerit condimentum augue, at elementum felis placerat ac. Cras scelerisque eu urna in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et neque ac diam suscipit vehicula vel a tellus. Pellentesque et nibh ut quam condimentum placerat non non arcu. Sed tempus sapien id massa commodo, et finibus nibh ullamcorper. Pellentesque ac erat lobortis nibh fermentum malesuada in semper arcu.

Nulla facilisi. Aenean auctor commodo ipsum, nec scelerisque risus ornare ac. Donec ut dapibus augue, et tincidunt nibh. Sed placerat mauris vel ex accumsan, sit amet fringilla tortor rhoncus. Praesent non felis ut quam porttitor finibus eu nec lorem. Etiam a bibendum leo, vitae finibus lacus. Aliquam condimentum lorem leo, at malesuada nunc vestibulum a. Mauris euismod, nisi ut varius volutpat, est ex laoreet ligula, non bibendum turpis justo ut nulla. Aliquam erat volutpat. Maecenas lorem mi, fringilla sit amet ipsum sed.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dignissim quis enim vel bibendum. Aliquam dui mi, rutrum a nisl ac, tincidunt lacinia ipsum. Nulla est libero, fermentum mollis egestas vel, eleifend sed velit. Etiam gravida pretium sagittis. Donec elit velit, sollicitudin et justo vitae, finibus elementum leo. Quisque facilisis ut urna et molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur purus id leo hendrerit faucibus. Sed ullamcorper, neque tincidunt hendrerit suscipit, magna arcu bibendum elit, at lacinia risus velit facilisis erat. Suspendisse eu lorem eu leo interdum dignissim vel sit amet orci. Mauris dictum posuere urna, in interdum elit. Sed sed aliquam orci, et volutpat ligula. Vivamus ex neque, tristique quis luctus ornare, dictum ac purus.

Cras in lacus velit. Ut lobortis facilisis velit vitae tempus. Aenean laoreet aliquam luctus. In vulputate laoreet metus vitae iaculis. Nunc eget dolor molestie, ultrices turpis eget, lacinia nibh. Phasellus ornare, elit vestibulum ullamcorper auctor, est magna porttitor felis, faucibus dignissim lacus lectus id lorem. Duis dignissim lacus quis metus ultrices viverra in in magna. Nullam maximus convallis enim sit amet consequat. Vivamus ut lectus est. Ut a leo a augue faucibus imperdiet. Vestibulum in ligula at massa ultrices porta in eu mi. Morbi tincidunt varius sapien, quis faucibus dolor venenatis et. Nullam aliquam consectetur nulla.

Suspendisse enim est, aliquam eu eros ut, lacinia vulputate nisi. Quisque vel convallis risus. Phasellus vitae diam congue magna tincidunt hendrerit. Nam eget sem turpis. Nam tellus metus, pulvinar ut commodo a, viverra id dui. Morbi posuere odio erat, mollis pharetra nulla dictum non. Nullam dignissim auctor diam, id aliquam massa volutpat in. Pellentesque efficitur urna ut nulla consectetur pellentesque quis ac sapien. Sed sed ex dolor. Quisque quis velit nec quam euismod vehicula. Mauris semper tincidunt sodales. Vivamus sodales lacus vel urna vestibulum, vitae iaculis enim facilisis. Nulla ut magna vitae arcu pulvinar tristique id eu nibh. Suspendisse sed rutrum dolor. Aliquam lectus erat, viverra at lacus eu, luctus egestas ipsum. Morbi elementum mauris ac lorem sagittis laoreet.

Aliquam faucibus, lacus vitae vulputate venenatis, est eros gravida dui, at maximus urna libero ac sapien. Sed tempus nibh euismod, consectetur tellus in, cursus mauris. Donec velit tortor, volutpat vel enim eget, tempus efficitur ligula. Nulla elit libero, mollis a erat vitae, tempus posuere tortor. Morbi blandit odio massa, ut hendrerit est suscipit pellentesque. Nam ex lacus, cursus a lacus eu, efficitur ultrices ligula. Quisque egestas, ipsum vitae ornare semper, sem elit scelerisque mauris, a dictum ante neque sit amet felis. Cras nec sapien viverra mauris maximus varius. Morbi mi nisl, maximus tincidunt risus in, luctus lobortis tellus.

Proin eu ex arcu. Pellentesque posuere, magna vitae tempor varius, leo ligula viverra risus, sed tempor enim lacus in justo. Duis gravida ullamcorper bibendum. Integer facilisis nisi mollis enim tempus, sit amet tincidunt quam convallis. Donec hendrerit condimentum augue, at elementum felis placerat ac. Cras scelerisque eu urna in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et neque ac diam suscipit vehicula vel a tellus. Pellentesque et nibh ut quam condimentum placerat non non arcu. Sed tempus sapien id massa commodo, et finibus nibh ullamcorper. Pellentesque ac erat lobortis nibh fermentum malesuada in semper arcu.

Nulla facilisi. Aenean auctor commodo ipsum, nec scelerisque risus ornare ac. Donec ut dapibus augue, et tincidunt nibh. Sed placerat mauris vel ex accumsan, sit amet fringilla tortor rhoncus. Praesent non felis ut quam porttitor finibus eu nec lorem. Etiam a bibendum leo, vitae finibus lacus. Aliquam condimentum lorem leo, at malesuada nunc vestibulum a. Mauris euismod, nisi ut varius volutpat, est ex laoreet ligula, non bibendum turpis justo ut nulla. Aliquam erat volutpat. Maecenas lorem mi, fringilla sit amet ipsum sed." >temp1.txt
./xclone2 -m temp1.txt

echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dignissim quis enim vel bibendum. Aliquam dui mi, rutrum a nisl ac, tincidunt lacinia ipsum. Nulla est libero, fermentum mollis egestas vel, eleifend sed velit. Etiam gravida pretium sagittis. Donec elit velit, sollicitudin et justo vitae, finibus elementum leo. Quisque facilisis ut urna et molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur purus id leo hendrerit faucibus. Sed ullamcorper, neque tincidunt hendrerit suscipit, magna arcu bibendum elit, at lacinia risus velit facilisis erat. Suspendisse eu lorem eu leo interdum dignissim vel sit amet orci. Mauris dictum posuere urna, in interdum elit. Sed sed aliquam orci, et volutpat ligula. Vivamus ex neque, tristique quis luctus ornare, dictum ac purus.

Cras in lacus velit. Ut lobortis facilisis velit vitae tempus. Aenean laoreet aliquam luctus. In vulputate laoreet metus vitae iaculis. Nunc eget dolor molestie, ultrices turpis eget, lacinia nibh. Phasellus ornare, elit vestibulum ullamcorper auctor, est magna porttitor felis, faucibus dignissim lacus lectus id lorem. Duis dignissim lacus quis metus ultrices viverra in in magna. Nullam maximus convallis enim sit amet consequat. Vivamus ut lectus est. Ut a leo a augue faucibus imperdiet. Vestibulum in ligula at massa ultrices porta in eu mi. Morbi tincidunt varius sapien, quis faucibus dolor venenatis et. Nullam aliquam consectetur nulla.

Suspendisse enim est, aliquam eu eros ut, lacinia vulputate nisi. Quisque vel convallis risus. Phasellus vitae diam congue magna tincidunt hendrerit. Nam eget sem turpis. Nam tellus metus, pulvinar ut commodo a, viverra id dui. Morbi posuere odio erat, mollis pharetra nulla dictum non. Nullam dignissim auctor diam, id aliquam massa volutpat in. Pellentesque efficitur urna ut nulla consectetur pellentesque quis ac sapien. Sed sed ex dolor. Quisque quis velit nec quam euismod vehicula. Mauris semper tincidunt sodales. Vivamus sodales lacus vel urna vestibulum, vitae iaculis enim facilisis. Nulla ut magna vitae arcu pulvinar tristique id eu nibh. Suspendisse sed rutrum dolor. Aliquam lectus erat, viverra at lacus eu, luctus egestas ipsum. Morbi elementum mauris ac lorem sagittis laoreet.

Aliquam faucibus, lacus vitae vulputate venenatis, est eros gravida dui, at maximus urna libero ac sapien. Sed tempus nibh euismod, consectetur tellus in, cursus mauris. Donec velit tortor, volutpat vel enim eget, tempus efficitur ligula. Nulla elit libero, mollis a erat vitae, tempus posuere tortor. Morbi blandit odio massa, ut hendrerit est suscipit pellentesque. Nam ex lacus, cursus a lacus eu, efficitur ultrices ligula. Quisque egestas, ipsum vitae ornare semper, sem elit scelerisque mauris, a dictum ante neque sit amet felis. Cras nec sapien viverra mauris maximus varius. Morbi mi nisl, maximus tincidunt risus in, luctus lobortis tellus.

Proin eu ex arcu. Pellentesque posuere, magna vitae tempor varius, leo ligula viverra risus, sed tempor enim lacus in justo. Duis gravida ullamcorper bibendum. Integer facilisis nisi mollis enim tempus, sit amet tincidunt quam convallis. Donec hendrerit condimentum augue, at elementum felis placerat ac. Cras scelerisque eu urna in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et neque ac diam suscipit vehicula vel a tellus. Pellentesque et nibh ut quam condimentum placerat non non arcu. Sed tempus sapien id massa commodo, et finibus nibh ullamcorper. Pellentesque ac erat lobortis nibh fermentum malesuada in semper arcu.

Nulla facilisi. Aenean auctor commodo ipsum, nec scelerisque risus ornare ac. Donec ut dapibus augue, et tincidunt nibh. Sed placerat mauris vel ex accumsan, sit amet fringilla tortor rhoncus. Praesent non felis ut quam porttitor finibus eu nec lorem. Etiam a bibendum leo, vitae finibus lacus. Aliquam condimentum lorem leo, at malesuada nunc vestibulum a. Mauris euismod, nisi ut varius volutpat, est ex laoreet ligula, non bibendum turpis justo ut nulla. Aliquam erat volutpat. Maecenas lorem mi, fringilla sit amet ipsum sed.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dignissim quis enim vel bibendum. Aliquam dui mi, rutrum a nisl ac, tincidunt lacinia ipsum. Nulla est libero, fermentum mollis egestas vel, eleifend sed velit. Etiam gravida pretium sagittis. Donec elit velit, sollicitudin et justo vitae, finibus elementum leo. Quisque facilisis ut urna et molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur purus id leo hendrerit faucibus. Sed ullamcorper, neque tincidunt hendrerit suscipit, magna arcu bibendum elit, at lacinia risus velit facilisis erat. Suspendisse eu lorem eu leo interdum dignissim vel sit amet orci. Mauris dictum posuere urna, in interdum elit. Sed sed aliquam orci, et volutpat ligula. Vivamus ex neque, tristique quis luctus ornare, dictum ac purus.

Cras in lacus velit. Ut lobortis facilisis velit vitae tempus. Aenean laoreet aliquam luctus. In vulputate laoreet metus vitae iaculis. Nunc eget dolor molestie, ultrices turpis eget, lacinia nibh. Phasellus ornare, elit vestibulum ullamcorper auctor, est magna porttitor felis, faucibus dignissim lacus lectus id lorem. Duis dignissim lacus quis metus ultrices viverra in in magna. Nullam maximus convallis enim sit amet consequat. Vivamus ut lectus est. Ut a leo a augue faucibus imperdiet. Vestibulum in ligula at massa ultrices porta in eu mi. Morbi tincidunt varius sapien, quis faucibus dolor venenatis et. Nullam aliquam consectetur nulla.

Suspendisse enim est, aliquam eu eros ut, lacinia vulputate nisi. Quisque vel convallis risus. Phasellus vitae diam congue magna tincidunt hendrerit. Nam eget sem turpis. Nam tellus metus, pulvinar ut commodo a, viverra id dui. Morbi posuere odio erat, mollis pharetra nulla dictum non. Nullam dignissim auctor diam, id aliquam massa volutpat in. Pellentesque efficitur urna ut nulla consectetur pellentesque quis ac sapien. Sed sed ex dolor. Quisque quis velit nec quam euismod vehicula. Mauris semper tincidunt sodales. Vivamus sodales lacus vel urna vestibulum, vitae iaculis enim facilisis. Nulla ut magna vitae arcu pulvinar tristique id eu nibh. Suspendisse sed rutrum dolor. Aliquam lectus erat, viverra at lacus eu, luctus egestas ipsum. Morbi elementum mauris ac lorem sagittis laoreet.

Aliquam faucibus, lacus vitae vulputate venenatis, est eros gravida dui, at maximus urna libero ac sapien. Sed tempus nibh euismod, consectetur tellus in, cursus mauris. Donec velit tortor, volutpat vel enim eget, tempus efficitur ligula. Nulla elit libero, mollis a erat vitae, tempus posuere tortor. Morbi blandit odio massa, ut hendrerit est suscipit pellentesque. Nam ex lacus, cursus a lacus eu, efficitur ultrices ligula. Quisque egestas, ipsum vitae ornare semper, sem elit scelerisque mauris, a dictum ante neque sit amet felis. Cras nec sapien viverra mauris maximus varius. Morbi mi nisl, maximus tincidunt risus in, luctus lobortis tellus.

Proin eu ex arcu. Pellentesque posuere, magna vitae tempor varius, leo ligula viverra risus, sed tempor enim lacus in justo. Duis gravida ullamcorper bibendum. Integer facilisis nisi mollis enim tempus, sit amet tincidunt quam convallis. Donec hendrerit condimentum augue, at elementum felis placerat ac. Cras scelerisque eu urna in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et neque ac diam suscipit vehicula vel a tellus. Pellentesque et nibh ut quam condimentum placerat non non arcu. Sed tempus sapien id massa commodo, et finibus nibh ullamcorper. Pellentesque ac erat lobortis nibh fermentum malesuada in semper arcu.

Nulla facilisi. Aenean auctor commodo ipsum, nec scelerisque risus ornare ac. Donec ut dapibus augue, et tincidunt nibh. Sed placerat mauris vel ex accumsan, sit amet fringilla tortor rhoncus. Praesent non felis ut quam porttitor finibus eu nec lorem. Etiam a bibendum leo, vitae finibus lacus. Aliquam condimentum lorem leo, at malesuada nunc vestibulum a. Mauris euismod, nisi ut varius volutpat, est ex laoreet ligula, non bibendum turpis justo ut nulla. Aliquam erat volutpat. Maecenas lorem mi, fringilla sit amet ipsum sed." >temp1.txt
echo "abcdefghij" >/proc/enc_key_file
./xclone2 -me temp1.txt

echo "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dignissim quis enim vel bibendum. Aliquam dui mi, rutrum a nisl ac, tincidunt lacinia ipsum. Nulla est libero, fermentum mollis egestas vel, eleifend sed velit. Etiam gravida pretium sagittis. Donec elit velit, sollicitudin et justo vitae, finibus elementum leo. Quisque facilisis ut urna et molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur purus id leo hendrerit faucibus. Sed ullamcorper, neque tincidunt hendrerit suscipit, magna arcu bibendum elit, at lacinia risus velit facilisis erat. Suspendisse eu lorem eu leo interdum dignissim vel sit amet orci. Mauris dictum posuere urna, in interdum elit. Sed sed aliquam orci, et volutpat ligula. Vivamus ex neque, tristique quis luctus ornare, dictum ac purus.

Cras in lacus velit. Ut lobortis facilisis velit vitae tempus. Aenean laoreet aliquam luctus. In vulputate laoreet metus vitae iaculis. Nunc eget dolor molestie, ultrices turpis eget, lacinia nibh. Phasellus ornare, elit vestibulum ullamcorper auctor, est magna porttitor felis, faucibus dignissim lacus lectus id lorem. Duis dignissim lacus quis metus ultrices viverra in in magna. Nullam maximus convallis enim sit amet consequat. Vivamus ut lectus est. Ut a leo a augue faucibus imperdiet. Vestibulum in ligula at massa ultrices porta in eu mi. Morbi tincidunt varius sapien, quis faucibus dolor venenatis et. Nullam aliquam consectetur nulla.

Suspendisse enim est, aliquam eu eros ut, lacinia vulputate nisi. Quisque vel convallis risus. Phasellus vitae diam congue magna tincidunt hendrerit. Nam eget sem turpis. Nam tellus metus, pulvinar ut commodo a, viverra id dui. Morbi posuere odio erat, mollis pharetra nulla dictum non. Nullam dignissim auctor diam, id aliquam massa volutpat in. Pellentesque efficitur urna ut nulla consectetur pellentesque quis ac sapien. Sed sed ex dolor. Quisque quis velit nec quam euismod vehicula. Mauris semper tincidunt sodales. Vivamus sodales lacus vel urna vestibulum, vitae iaculis enim facilisis. Nulla ut magna vitae arcu pulvinar tristique id eu nibh. Suspendisse sed rutrum dolor. Aliquam lectus erat, viverra at lacus eu, luctus egestas ipsum. Morbi elementum mauris ac lorem sagittis laoreet.

Aliquam faucibus, lacus vitae vulputate venenatis, est eros gravida dui, at maximus urna libero ac sapien. Sed tempus nibh euismod, consectetur tellus in, cursus mauris. Donec velit tortor, volutpat vel enim eget, tempus efficitur ligula. Nulla elit libero, mollis a erat vitae, tempus posuere tortor. Morbi blandit odio massa, ut hendrerit est suscipit pellentesque. Nam ex lacus, cursus a lacus eu, efficitur ultrices ligula. Quisque egestas, ipsum vitae ornare semper, sem elit scelerisque mauris, a dictum ante neque sit amet felis. Cras nec sapien viverra mauris maximus varius. Morbi mi nisl, maximus tincidunt risus in, luctus lobortis tellus.

Proin eu ex arcu. Pellentesque posuere, magna vitae tempor varius, leo ligula viverra risus, sed tempor enim lacus in justo. Duis gravida ullamcorper bibendum. Integer facilisis nisi mollis enim tempus, sit amet tincidunt quam convallis. Donec hendrerit condimentum augue, at elementum felis placerat ac. Cras scelerisque eu urna in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et neque ac diam suscipit vehicula vel a tellus. Pellentesque et nibh ut quam condimentum placerat non non arcu. Sed tempus sapien id massa commodo, et finibus nibh ullamcorper. Pellentesque ac erat lobortis nibh fermentum malesuada in semper arcu.

Nulla facilisi. Aenean auctor commodo ipsum, nec scelerisque risus ornare ac. Donec ut dapibus augue, et tincidunt nibh. Sed placerat mauris vel ex accumsan, sit amet fringilla tortor rhoncus. Praesent non felis ut quam porttitor finibus eu nec lorem. Etiam a bibendum leo, vitae finibus lacus. Aliquam condimentum lorem leo, at malesuada nunc vestibulum a. Mauris euismod, nisi ut varius volutpat, est ex laoreet ligula, non bibendum turpis justo ut nulla. Aliquam erat volutpat. Maecenas lorem mi, fringilla sit amet ipsum sed.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus dignissim quis enim vel bibendum. Aliquam dui mi, rutrum a nisl ac, tincidunt lacinia ipsum. Nulla est libero, fermentum mollis egestas vel, eleifend sed velit. Etiam gravida pretium sagittis. Donec elit velit, sollicitudin et justo vitae, finibus elementum leo. Quisque facilisis ut urna et molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam consectetur purus id leo hendrerit faucibus. Sed ullamcorper, neque tincidunt hendrerit suscipit, magna arcu bibendum elit, at lacinia risus velit facilisis erat. Suspendisse eu lorem eu leo interdum dignissim vel sit amet orci. Mauris dictum posuere urna, in interdum elit. Sed sed aliquam orci, et volutpat ligula. Vivamus ex neque, tristique quis luctus ornare, dictum ac purus.

Cras in lacus velit. Ut lobortis facilisis velit vitae tempus. Aenean laoreet aliquam luctus. In vulputate laoreet metus vitae iaculis. Nunc eget dolor molestie, ultrices turpis eget, lacinia nibh. Phasellus ornare, elit vestibulum ullamcorper auctor, est magna porttitor felis, faucibus dignissim lacus lectus id lorem. Duis dignissim lacus quis metus ultrices viverra in in magna. Nullam maximus convallis enim sit amet consequat. Vivamus ut lectus est. Ut a leo a augue faucibus imperdiet. Vestibulum in ligula at massa ultrices porta in eu mi. Morbi tincidunt varius sapien, quis faucibus dolor venenatis et. Nullam aliquam consectetur nulla.

Suspendisse enim est, aliquam eu eros ut, lacinia vulputate nisi. Quisque vel convallis risus. Phasellus vitae diam congue magna tincidunt hendrerit. Nam eget sem turpis. Nam tellus metus, pulvinar ut commodo a, viverra id dui. Morbi posuere odio erat, mollis pharetra nulla dictum non. Nullam dignissim auctor diam, id aliquam massa volutpat in. Pellentesque efficitur urna ut nulla consectetur pellentesque quis ac sapien. Sed sed ex dolor. Quisque quis velit nec quam euismod vehicula. Mauris semper tincidunt sodales. Vivamus sodales lacus vel urna vestibulum, vitae iaculis enim facilisis. Nulla ut magna vitae arcu pulvinar tristique id eu nibh. Suspendisse sed rutrum dolor. Aliquam lectus erat, viverra at lacus eu, luctus egestas ipsum. Morbi elementum mauris ac lorem sagittis laoreet.

Aliquam faucibus, lacus vitae vulputate venenatis, est eros gravida dui, at maximus urna libero ac sapien. Sed tempus nibh euismod, consectetur tellus in, cursus mauris. Donec velit tortor, volutpat vel enim eget, tempus efficitur ligula. Nulla elit libero, mollis a erat vitae, tempus posuere tortor. Morbi blandit odio massa, ut hendrerit est suscipit pellentesque. Nam ex lacus, cursus a lacus eu, efficitur ultrices ligula. Quisque egestas, ipsum vitae ornare semper, sem elit scelerisque mauris, a dictum ante neque sit amet felis. Cras nec sapien viverra mauris maximus varius. Morbi mi nisl, maximus tincidunt risus in, luctus lobortis tellus.

Proin eu ex arcu. Pellentesque posuere, magna vitae tempor varius, leo ligula viverra risus, sed tempor enim lacus in justo. Duis gravida ullamcorper bibendum. Integer facilisis nisi mollis enim tempus, sit amet tincidunt quam convallis. Donec hendrerit condimentum augue, at elementum felis placerat ac. Cras scelerisque eu urna in faucibus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque et neque ac diam suscipit vehicula vel a tellus. Pellentesque et nibh ut quam condimentum placerat non non arcu. Sed tempus sapien id massa commodo, et finibus nibh ullamcorper. Pellentesque ac erat lobortis nibh fermentum malesuada in semper arcu.

Nulla facilisi. Aenean auctor commodo ipsum, nec scelerisque risus ornare ac. Donec ut dapibus augue, et tincidunt nibh. Sed placerat mauris vel ex accumsan, sit amet fringilla tortor rhoncus. Praesent non felis ut quam porttitor finibus eu nec lorem. Etiam a bibendum leo, vitae finibus lacus. Aliquam condimentum lorem leo, at malesuada nunc vestibulum a. Mauris euismod, nisi ut varius volutpat, est ex laoreet ligula, non bibendum turpis justo ut nulla. Aliquam erat volutpat. Maecenas lorem mi, fringilla sit amet ipsum sed." >temp1.txt
./xclone2 -mc temp1.txt

echo "jihgfedcba" >/proc/enc_key_file
./xclone2 -mce temp1.txt


./xclone2 -p /usr/trashbin


